### ISSUE TITLE
Resume checkpoint

### ISSUE THREAD

**Issue by valeriopaolicelli** [guoweiyu/Context-Enhanced-Stereo-Transformer#1]
Hi,

thank you for sharing your code. I'm trying to load your checkpoint but I get
```
>>> torch.load('epoch_15_model.pth.tar')
RuntimeError: [enforce fail at inline_container.cc:145] . PytorchStreamReader failed reading zip archive: failed finding central directory
```
Do you know what the problem could be? Maybe the file on GDrive is corrupt?
I'm using Python 3.8 and PyTorch 1.9.0.

**Comment by mattpoggi** [comment]
Hi, same problem here.

**Comment by guoweiyu** [comment]
Sorry for the late reply. 
Sorry, this is because the file was damaged during the upload process, 
I uploaded the model again and rechecked it.
Thanks for pointing this out! @mattpoggi @valeriopaolicelli

**Comment by valeriopaolicelli** [comment]
Now it works for me, thanks @guoweiyu ! 

FYI you are still linking the damaged file [here](https://github.com/guoweiyu/Context-Enhanced-Stereo-Transformer/blob/4b72008abb798d98f364fed8571927cb550e9f65/README.md?plain=1#L49)
