### ISSUE TITLE
RuntimeError: stack expects each tensor to be equal size, but got [3, 390, 771] at entry 0 and [3, 371, 880] at entry 1

### ISSUE THREAD

**Issue by CHXAdmin** [guoweiyu/Context-Enhanced-Stereo-Transformer#3]
batch size  = 2 will cause this ,when batch size =1 ,it can run

**Comment by guoweiyu** [comment]
Thanks for your question!
If you use different shape images in one batch, you should resize them to the same shape before input to the model
